update=2/14/2017 11:41:26 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=D:/Software/KiCAD_Libraries
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=MyKiCADLibs/Components/ESP8266
LibName31=MyKiCADLibs/Components/mq_snsr
LibName32=MyKiCADLibs/Components/tgs2602
LibName33=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName34=C:/Program Files/KiCad/share/kicad/library/74xx
LibName35=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName36=C:/Program Files/KiCad/share/kicad/library/actel
LibName37=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName38=C:/Program Files/KiCad/share/kicad/library/allegro
LibName39=C:/Program Files/KiCad/share/kicad/library/Altera
LibName40=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName41=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName42=C:/Program Files/KiCad/share/kicad/library/Arduino_As_Uno-cache
LibName43=C:/Program Files/KiCad/share/kicad/library/Arduino_Nano-cache
LibName44=C:/Program Files/KiCad/share/kicad/library/Arduino_Pro_Mini-cache
LibName45=C:/Program Files/KiCad/share/kicad/library/atmel
LibName46=C:/Program Files/KiCad/share/kicad/library/audio
LibName47=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName48=C:/Program Files/KiCad/share/kicad/library/bbd
LibName49=C:/Program Files/KiCad/share/kicad/library/bosch
LibName50=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName51=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName52=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName53=C:/Program Files/KiCad/share/kicad/library/conn
LibName54=C:/Program Files/KiCad/share/kicad/library/contrib
LibName55=C:/Program Files/KiCad/share/kicad/library/cypress
LibName56=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName57=C:/Program Files/KiCad/share/kicad/library/device
LibName58=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName59=C:/Program Files/KiCad/share/kicad/library/diode
LibName60=C:/Program Files/KiCad/share/kicad/library/display
LibName61=C:/Program Files/KiCad/share/kicad/library/dsp
LibName62=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName63=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName64=C:/Program Files/KiCad/share/kicad/library/ESP8266
LibName65=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName66=C:/Program Files/KiCad/share/kicad/library/gennum
LibName67=C:/Program Files/KiCad/share/kicad/library/graphic
LibName68=C:/Program Files/KiCad/share/kicad/library/hc11
LibName69=C:/Program Files/KiCad/share/kicad/library/intel
LibName70=C:/Program Files/KiCad/share/kicad/library/interface
LibName71=C:/Program Files/KiCad/share/kicad/library/ir
LibName72=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName73=C:/Program Files/KiCad/share/kicad/library/linear
LibName74=C:/Program Files/KiCad/share/kicad/library/logo
LibName75=C:/Program Files/KiCad/share/kicad/library/maxim
LibName76=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName77=C:/Program Files/KiCad/share/kicad/library/memory
LibName78=C:/Program Files/KiCad/share/kicad/library/microchip
LibName79=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName80=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName81=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName82=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName83=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName84=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName85=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName86=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName87=C:/Program Files/KiCad/share/kicad/library/motorola
LibName88=C:/Program Files/KiCad/share/kicad/library/motors
LibName89=C:/Program Files/KiCad/share/kicad/library/mq_snsr
LibName90=C:/Program Files/KiCad/share/kicad/library/msp430
LibName91=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName92=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName93=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName94=C:/Program Files/KiCad/share/kicad/library/opto
LibName95=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName96=C:/Program Files/KiCad/share/kicad/library/philips
LibName97=C:/Program Files/KiCad/share/kicad/library/power
LibName98=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName99=C:/Program Files/KiCad/share/kicad/library/powerint
LibName100=C:/Program Files/KiCad/share/kicad/library/pspice
LibName101=C:/Program Files/KiCad/share/kicad/library/references
LibName102=C:/Program Files/KiCad/share/kicad/library/regul
LibName103=C:/Program Files/KiCad/share/kicad/library/relays
LibName104=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName105=C:/Program Files/KiCad/share/kicad/library/sensors
LibName106=C:/Program Files/KiCad/share/kicad/library/silabs
LibName107=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName108=C:/Program Files/KiCad/share/kicad/library/stm8
LibName109=C:/Program Files/KiCad/share/kicad/library/stm32
LibName110=C:/Program Files/KiCad/share/kicad/library/supertex
LibName111=C:/Program Files/KiCad/share/kicad/library/switches
LibName112=C:/Program Files/KiCad/share/kicad/library/texas
LibName113=C:/Program Files/KiCad/share/kicad/library/tgs2602
LibName114=C:/Program Files/KiCad/share/kicad/library/transf
LibName115=C:/Program Files/KiCad/share/kicad/library/transistors
LibName116=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName117=C:/Program Files/KiCad/share/kicad/library/valves
LibName118=C:/Program Files/KiCad/share/kicad/library/video
LibName119=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName120=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName121=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName122=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName123=C:/Program Files/KiCad/share/kicad/library/zetex
LibName124=C:/Program Files/KiCad/share/kicad/library/Zilog
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceAjustPassiveValues=0
LabSize=60
ERC_TestSimilarLabels=1
